Revert "audio: Set up correct defaults for 32bit service"
This reverts commit 9cc7a137912e5a0e74cdf53a06cb846d3d49d7e0.

Reason:

error: hardware/interfaces/audio/common/all-versions/default/service/Android.bp:74:13: property "defaults" already defined

error: hardware/interfaces/audio/common/all-versions/default/service/Android.bp:44:13: <-- previous definition here

Change-Id: Id80d2ba406d42e13ebf564b90b43020b5e594fa1